version: '3'

services:
  api:
    tty: true
    build: .
    security_opt:
      - seccomp:unconfined
    ports:
      - "9000:9000"
    volumes:
      - ".:/workspace"
    environment:
      - "DB_URL=jdbc:postgresql://db/scala_on_ddd_dev"
    stdin_open: true
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: DockerfileDb
    ports:
      - "9010:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
    driver: local